import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import "./globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className="min-h-screen bg-slate-50">

            <div className="pb-16">
                {children}
            </div>

            <div className="fixed bottom-0 left-0 right-0 z-50">
                <Navbar />
            </div>

        </body>
        </html>
    );
}